---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: contents/basepage/about
  label: About
  match: "**/*"
- type: directory
  path: contents/portfolio
  label: Portfolio
  create: all
  match: "**/*"
- type: directory
  path: contents/blog
  label: Blog
  create: all
  match: "**/*"
- type: directory
  path: contents
  label: Content
  create: all
  match: "**/*"
  new_doc_ext: mdx
upload_dir: static/images
public_path: "/static"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
